### ISSUE TITLE
Change plus minus symbol in the prior vs posterior table view

### ISSUE THREAD

**Issue by IvanHeriver** [BaRatin-tools/BaRatinAGE#12]
This minor change suggestion is mentioned in issue #10 .

**Comment by IvanHeriver** [comment]
Changing the the current `+/-` is indeed easy to do. Is the symbole mentioned [here](https://en.wikipedia.org/wiki/Plus%E2%80%93minus_sign), i.e. `±`, what you're refering to @JeromeLeCoz ?

**Comment by JeromeLeCoz** [comment]
Yes

**Comment by IvanHeriver** [comment]
done
