### ISSUE TITLE
Update help files

### ISSUE THREAD

**Issue by benRenard** [BaRatin-tools/BaRatinAGE#14]
Some help files probably need some updating to reflect changes made in v2-2. In particular, 'overview', 'going further' and 'FAQ' are partially out-of-date due to new licence / Linux version / MCMC export. Need to check other pages too.

**Comment by JeromeLeCoz** [comment]
I have just updated the 'overview' and 'FAQ'. I had updated the ref list in "going further' previously. Maybe describing the file formats would be useful?

The images in subfolder /img also need to be updated. I have updated some of the English help images using my new favourite study case (Aisne at Verrières). However, I have not processed any stage series (could be retrieved from Hydroportail).

To be continued..............
[Aisne_Verrieres.bar.zip](https://github.com/BaRatin-tools/BaRatinAGE/files/10156408/Aisne_Verrieres.bar.zip)

**Comment by JeromeLeCoz** [comment]
We should take the list of v2-2 new features and check they are described in the help files.

**Comment by benRenard** [comment]
For the new example (Aisne at Verrières), be careful that you have to resize all figures (they are currently too large). The alternative would be to do some proper html/css handling of this, but I think we should not do it now given that help files will probably be heavily modified in v3.

**Comment by IvanHeriver** [comment]
no need to change the size of the png images I think... I recommend just adding the following line of css in the styles.css file:

```css
img {
  max-width: 100%;
}

```

**Comment by JeromeLeCoz** [comment]
Works fine, thx! I set max width to 80%.

I have processed a time series for the Verrieres example so I'll be able to change all the figures in the help files.

**Comment by JeromeLeCoz** [comment]
Here is my Verrières case file.

[Aisne_Verrieres.bar.zip](https://github.com/BaRatin-tools/BaRatinAGE/files/10185860/Aisne_Verrieres.bar.zip)

**Comment by IvanHeriver** [comment]
> All figures updated except the plot legends (I don't have the later ones in my version of BaRatinAGE). Ivan can you update them please?

Not sure to understand what you mean... I commited and pushed the new legends (png files) two days ago (see commit https://github.com/BaRatin-tools/BaRatinAGE/commit/0a2dabee0bdac980ca4ab96043eacbd09d2011b1)...

**Comment by JeromeLeCoz** [comment]
Sorry, I had not seen you already did it! All done then.

**Comment by benRenard** [comment]
I updated help files (both en and fr, see [here](https://github.com/BaRatin-tools/BaRatinAGE/commit/4f989dbdfcad9969ffb650b8f95b7e30f7e3ca34)), but the following still needs to be done by you Jérôme, mostly to reflect the new example (Verrière instead of Sauze):
1. Update many image files in French (in help/fr/img). The easy fix is to copy-paste the English versions which have all been updated, but that's not enough if we want screenshots of the French version of BaRatinAGE. I didn't do it myself because the apparence is a bit different on Linux and I wanted to remain consistent, but here is a list of the files that need updating:
     - [ ]  MainWindow_full.png
     - [ ]  Matrix_diag.png
     - [ ]  Matrix_ok.png
     - [ ]  PriorAssistant.png   
     - [ ]  PriorRC.png 
     - [ ]  Gaugings.png. For this one you may also want to redo a screenshot of the English version so that the file name is Verrieres_gaugings.csv rather than XY.BAD
     - [ ] PosteriorRC.png
     - [ ] PriorVsPost_Parameters.png is missing
     - [ ] MCMCtraces.png
     - [ ] Spaghetti_post.png
2. The last paragraph of FlowSeries.html needs to be rewritten (in both en and fr). Moreover, I would find it more logical to show the figure for the April-May event since this is the one that was used in the "Limni" page
3.  The Gaugings and limni csv files needs to be added to the folder example. To avoid re-changing anything to the help html files, please make sure they are named Verrieres_gaugings.csv and Verrieres_limni_april_may_2022.csv
4. In FAQ.html (both fr and en), section "Training", can you provide links to the material in English, French and Spanish, or explain how to get them?

**Comment by JeromeLeCoz** [comment]
4. Done

3. I see you've done it, Ben. I'm not adding the other limni creation example (from HYDRO3 using Excel), to be provided elsewhere.

1 & 2: will do

**Comment by JeromeLeCoz** [comment]
1. Done

Verrieres_gaugings.csv modified to discard the 2021 July gauging.

PriorPostRC comparison plot added.

PriorPostTable plot should be presented in help files (did not exist). Created for both en/fr.

Also added for inclusion in help files: Remarks (en/fr)

**Comment by JeromeLeCoz** [comment]
2. Done (Ben, please check my new comment)...

I zoomed on the small flood peak to make the yellow intervals visible... but there is less to say than previously with the Sauze example.

**Comment by benRenard** [comment]
Looking great!

1 problem remained: file PriorVsPost_parameters.png was written PriorVsPost_Parameters.png (uppercase P)  in the link in the html files (en and fr) - fixed in last commit.

**Comment by IvanHeriver** [comment]
Are we good to go? I'll close the issue if no more adjustements are required.

**Comment by JeromeLeCoz** [comment]
Yes, I think this is it for v2.2.1. However, for future versions, it would be good to cover a few more features in the help files:

* the import and export operations
* the ASCII file formats
* some "other plots" not presented in the help files

**Comment by benRenard** [comment]
OK, I'm removing the v2.2 milestone but leaving the ticket open for these suggestions

**Comment by benRenard** [comment]
I'm closing the ticket, the remaining suggestions seems irrelevant now with v3
