### ISSUE TITLE
Back to full size seems a bit tighter than initial view (plots)

### ISSUE THREAD

**Issue by JeromeLeCoz** [BaRatin-tools/BaRatinAGE#18]
nitpicks: at least on the flow series plot, I have the impression that the return to the initial view is done on the MaxPost curve but truncates the highest uncertainty envelopes (whereas when you open the graph for the first time, or re-open it, the framing seems wider and ok).

**Comment by IvanHeriver** [comment]
this is still an issue in BaRatinAGE V2. However this is fixed in BaRatinAGE v3?

Worth the effort for V2? Or should I close this issue?

**Comment by benRenard** [comment]
I think it can be closed - overall, I think it's not worth fixing such minor bugs in v2 if it's fixed in v3.
