### ISSUE TITLE
[linux-only] Colors of control matrix are incorrect 

### ISSUE THREAD

**Issue by benRenard** [BaRatin-tools/BaRatinAGE#21]
On Linux, the coloring of the cells of the control matrix do not work as expected. In particular, the light green color does not appear where it should. No problem in Windows, so this may have something to do with Linux look-and-feel and the way it refreshes itself.

I tried for hours to fix this with no success... The main conclusion of this attempt is that BaRatinAGE code looks OK in the sense that the color assigned to each cell is the expected one. And then something happens at the level of Javaswing rendering, but I couldn't understand what...

**Comment by IvanHeriver** [comment]
closing this issue as I think it is no longer relevant for 3.0 versions of BaRatinAGE. Feel free to reopen if needed.
