### ISSUE TITLE
Right-click menu in jfreechart panels should follow the selected langage

### ISSUE THREAD

**Issue by benRenard** [BaRatin-tools/BaRatinAGE#27]
Last time I checked (years ago!), this was not possible:
"At the moment, the localisation files are loaded statically according to the default locale. There's no option to configure on-the-fly the locale/language for a given chart or chart-panel. It would be a nice feature to have."

**Comment by IvanHeriver** [comment]
This is fixed in BaRatinAGE v3 since the default JFreeChart context menu was removed to the profite of a custom menu which is now correclty translated.
