### ISSUE TITLE
Version 2.2.1 Notes

### ISSUE THREAD

**Issue by benRenard** [BaRatin-tools/BaRatinAGE#44]
The main novelties of v2.2.1 are summarized below, and I was thinking using this text as version notes accompanying the release. Please have a look and correct, complete and reorder as you see fit. I'll do a French translation as well (unless you wanna go for it, in which case please help yourself!) 
Also question: do we publish the list of persons who helped with translations, and if so where? I was thinking maybe as a big "thank you" at the end or the beginning of these version notes?

* BaRatinAGE and BaRatin become open-source (GPL3 license) and are available at https://github.com/BaRatin-tools
* BaRatinAGE is now available on Linux
* BaRatinAGE is now "stand-alone": it should work out-of-the-box on any (at least most!) Windows/Linux computers as it does not depend on a locally-installed version of Java anymore
* Rating curve can now be exported as an equation
* MCMC simulations can now be exported
* Unfeasible values are now removed before computing uncertainty envelops, unless they represent more than 75% of values
* Offset parameters "b" are now displayed in figures and tables (in addition to parameters k-a-c) 
* A new prior vs. posterior consistency check is available (see More Plots...Remarks in the Rating Curve panel)
* Comma-separated .csv files are now supported for gaugings and stage time series (in addition to semicolon-separated ones)
* "SaveSpaghetti" option was not working and has been fixed
* New languages can now be added "on-the-fly", by just completing lang/dico.txt and providing help files in help/mylanguage (if not provided, fallback is English)
* This version ships with 10 languages, validated by native speakers (fr, en, es, de, it, br, ko, hb, cn, jp)
* New "purely proportional" remnant error model, with sigma = gamma*Q
* Color of prior activation stages has changed (to clarify that they are not the same as the posterior activation stages)
* Specifying non-increasing prior activation stages triggers an error message when attempting to compute the prior rating curve
* "useManning" preference (from menu Options...Preferences) was not handled properly and has been deactivated until a proper fix is implemented
* A warning message is issued before computing hydrographs if the (roughly) estimated disk space is above 10MB
* A warning message is issued before changing the number of controls
* Added a template .xls file to create a stage time series .csv file
* Various minor ergonomic improvements
* Updating of help files to reflect all these changes

**Comment by JeromeLeCoz** [comment]
I think a big thank you in version notes is a good option (cf. list of contributors).

Minor edits:

-     BaRatinAGE and BaRatin become open-source (GPL3 license) and are available at https://github.com/BaRatin-tools
-     BaRatinAGE is now available on Linux
-     BaRatinAGE is now "stand-alone": it should work out-of-the-box on any (at least most!) Windows/Linux computers as it does not depend on a locally-installed version of Java anymore
-     Rating curve can now be exported as an equation
-     MCMC simulations can now be exported
-     Unfeasible values are now removed before computing uncertainty envelops **for the rating curve plots**, unless they represent more than 75% of values
-     Offset parameters "b" are now displayed in figures and tables (in addition to parameters k-a-c)
-     A new prior vs. posterior consistency check is available (see More Plots...Remarks in the Rating Curve panel)
-     Comma-separated .csv files are now supported for gaugings and stage time series (in addition to semicolon-separated ones)
-     "SaveSpaghetti" option was not working and has been fixed
-     New languages can now be added "on-the-fly", by just completing lang/dico.txt and providing help files in help/mylanguage (if not provided, fallback is English)
-     **This version ships with 26 languages, 12 being validated by native speakers (fr=French, en=English, es=Spanish, de=German, it=Italian, br=Portuguese (Brazil), cz=Czech, pl=Polish, ko=Korean, cn=Chinese, jp=Japanese, hb=Hebrew), 14 awaiting verification (ab=Arabic, ro=Romanian, nl=Dutch, sb=Serbian, mg=Hungarian, sl=Slovenian, sk=Slovak, fi=Finnish, et=Estonian, ru=Russian, uk=Ukrainian, sw=Swedish, am=Armenian, fs=Persian).**
-     New "purely proportional" remnant error model, with sigma = gamma*Q
-     Color of prior activation stages has changed (to clarify that they are not the same as the posterior activation stages)
-     Specifying non-increasing prior activation stages triggers an error message when attempting to compute the prior rating curve
-     "useManning" preference (from menu Options...Preferences) was not handled properly and has been deactivated until a proper fix is implemented
-     A warning message is issued before computing hydrographs if the (roughly) estimated disk space is above 10MB
-     A warning message is issued before changing the number of controls
-     Added a template .xls file to create a stage time series .csv file
-     Various minor ergonomic improvements
-     Updating of help files to reflect all these changes

**Comment by JeromeLeCoz** [comment]
Sorry, trying a better display of text:


BaRatinAGE and BaRatin become open-source (GPL3 license) and are available at https://github.com/BaRatin-tools

BaRatinAGE is now available on Linux

BaRatinAGE is now "stand-alone": it should work out-of-the-box on any (at least most!) Windows/Linux computers as it does not depend on a locally-installed version of Java anymore

Rating curve can now be exported as an equation

MCMC simulations can now be exported

Unfeasible values are now removed before computing uncertainty envelops **for the rating curve plots**, unless they represent more than 75% of values

Offset parameters "b" are now displayed in figures and tables (in addition to parameters k-a-c)

A new prior vs. posterior consistency check is available (see More Plots...Remarks in the Rating Curve panel)

Comma-separated .csv files are now supported for gaugings and stage time series (in addition to semicolon-separated ones)

"SaveSpaghetti" option was not working and has been fixed

New languages can now be added "on-the-fly", by just completing lang/dico.txt and providing help files in help/mylanguage (if not provided, fallback is English)

**This version ships with 26 languages, 12 being validated by native speakers (fr=French, en=English, es=Spanish, de=German, it=Italian, br=Portuguese (Brazil), cz=Czech, pl=Polish, ko=Korean, cn=Chinese, jp=Japanese, hb=Hebrew), 14 awaiting verification (ab=Arabic, ro=Romanian, nl=Dutch, sb=Serbian, mg=Hungarian, sl=Slovenian, sk=Slovak, fi=Finnish, et=Estonian, ru=Russian, uk=Ukrainian, sw=Swedish, am=Armenian, fs=Persian).**

New "purely proportional" remnant error model, with sigma = gamma*Q

Color of prior activation stages has changed (to clarify that they are not the same as the posterior activation stages)

Specifying non-increasing prior activation stages triggers an error message when attempting to compute the prior rating curve

"useManning" preference (from menu Options...Preferences) was not handled properly and has been deactivated until a proper fix is implemented

A warning message is issued before computing hydrographs if the (roughly) estimated disk space is above 10MB

A warning message is issued before changing the number of controls

Added a template .xls file to create a stage time series .csv file

Various minor ergonomic improvements

Updating of help files to reflect all these changes

**Comment by JeromeLeCoz** [comment]
Update:

This version ships with 26 languages, 13 being validated by native speakers (fr=French, en=English, es=Spanish, de=German, it=Italian, br=Portuguese (Brazil), cz=Czech, pl=Polish, ko=Korean, cn=Chinese, jp=Japanese, hb=Hebrew, fi=Finnish), 14 awaiting verification (ab=Arabic, ro=Romanian, nl=Dutch, sb=Serbian, mg=Hungarian, sl=Slovenian, sk=Slovak, et=Estonian, ru=Russian, uk=Ukrainian, sw=Swedish, am=Armenian, fs=Persian).

**Comment by JeromeLeCoz** [comment]
Update:

This version ships with 26 languages, 15 being validated by native speakers (fr=French, en=English, es=Spanish, de=German, it=Italian, br=Portuguese (Brazil), cz=Czech, pl=Polish, ro=Romanian, ko=Korean, cn=Chinese, jp=Japanese, hb=Hebrew, fi=Finnish, fa=Persian), 11 awaiting verification (ab=Arabic, nl=Dutch, sb=Serbian, mg=Hungarian, sl=Slovenian, sk=Slovak, et=Estonian, ru=Russian, uk=Ukrainian, sw=Swedish, am=Armenian).

**Comment by JeromeLeCoz** [comment]
Proposition de version française:

BaRatinAGE et BaRatin deviennent open-source (licence GPL3) et sont disponibles à l'adresse https://github.com/BaRatin-tools.

BaRatinAGE est maintenant disponible sur Linux

BaRatinAGE est maintenant "autonome" : il devrait fonctionner sur n'importe quel ordinateur (au moins la plupart !) Windows/Linux car il ne dépend plus d'une version de Java installée localement.

La courbe de tarage peut maintenant être exportée sous forme d'équation.

Les simulations MCMC peuvent maintenant être exportées

Les tirages de valeurs infaisables sont maintenant supprimés avant de calculer les enveloppes d'incertitude pour les tracés de la courbe de tarage, à moins qu'ils ne représentent plus de 75 % des valeurs.

Les paramètres offsets "b" sont maintenant affichés dans les figures et les tableaux (en plus des paramètres k-a-c).

Une nouvelle vérification de la cohérence entre les aprioris et les apostérioris est disponible (voir Autres graphiques...Remarques dans le panneau Courbe de tarage).

Les fichiers .csv séparés par des virgules sont maintenant supportés pour les jaugeages et les séries de hauteur (en plus des fichiers séparés par des points-virgules).

L'option "SaveSpaghetti" ne fonctionnait pas et a été corrigée.

De nouvelles langues peuvent maintenant être ajoutées "à la volée", en remplissant simplement le fichier lang/dico.txt et en fournissant des fichiers d'aide dans help/mylanguage (s'il n'y en a pas, l'anglais est utilisé par défaut).

**Comment by JeromeLeCoz** [comment]
Update:
Update:

This version ships with 27 languages, 17 being validated by native speakers (fr=French, en=English, es=Spanish, cn=Chinese, ru=Russian, bg=Bulgarian, br=Portuguese (Brazil), cz=Czech, de=German, fa=Persian, fi=Finnish, hb=Hebrew, it=Italian, jp=Japanese, ko=Korean, pl=Polish, ro=Romanian), 10 awaiting verification (ab=Arabic, am=Armenian, et=Estonian, mg=Hungarian, nl=Dutch, sb=Serbian, sk=Slovak, sl=Slovenian, sw=Swedish, uk=Ukrainian).

**Comment by JeromeLeCoz** [comment]
Fin de la version française (désolé j'avais tronqué...):

Cette version est livrée avec 27 langues, 17 étant validées par des locuteurs natifs (fr=français, en=anglais, es=espagnol, cn=chinois, ru=russe, bg=bulgare, br=portugais (Brésil), cz=tchèque, de=allemand, fa=persan, fi=finnois, hb=hébreu, it=italien, jp=japonais, ko=coréen, pl=polonais, ro=roumain), et 10 en attente de vérification (ab=arabe, am=arménien, et=estonien, mg=hongrois, nl=néerlandais, sb=serbe, sk=slovaque, sl=slovène, sw=suédois, uk=ukrainien).

Nouveau modèle d'erreur restante "purement proportionnel", avec sigma = gamma*Q

La couleur des hauteurs d'activation a priori a changé (pour clarifier qu'elles ne sont pas les mêmes que les hauteurs d'activation a posteriori)

La spécification de hauteurs d'activation a priori non croissantes déclenche un message d'erreur lors de la tentative de calcul de la courbe de tarage a priori

La préférence "useManning" (du menu Options...Préférences) n'ayant pas été implémentée correctement, elle a été désactivée jusqu'à ce qu'un correctif adéquat soit mis en place.

Un message d'avertissement est émis avant de calculer les hydrogrammes si l'espace disque estimé (approximativement) est supérieur à 10 Mo.

Un message d'avertissement est émis avant de modifier le nombre de contrôles.

Ajout d'un modèle de fichier .xls pour créer un fichier .csv de séries de hauteur (limnigramme).

**Comment by benRenard** [comment]
OK I'm closing the ticket, definitive version notes can be found at https://github.com/BaRatin-tools/BaRatinAGE/releases/tag/v2.2.1
