### ISSUE TITLE
stage series display bug?

### ISSUE THREAD

**Issue by JeromeLeCoz** [BaRatin-tools/BaRatinAGE#45]
Hi

I don't understand why I get this strange oscillation in this stage series. Do you reproduce the bug? Do you see the problem?

![image](https://user-images.githubusercontent.com/86300732/209366280-6e41e270-c15e-41fd-9974-d0e49788aa79.png)
[Aisne_Berry_limni_crue_2021.csv](https://github.com/BaRatin-tools/BaRatinAGE/files/10296156/Aisne_Berry_limni_crue_2021.csv)

**Comment by IvanHeriver** [comment]
I think I see the problem with BaRatinAGE V2.2. Around timestamp 2021,5835 for example?

In BaRatinAGE v3, this issue seems gone. do you confirm?

**Comment by IvanHeriver** [comment]
Hi @JeromeLeCoz , 

- could you tell me if this bug is also found in v3?
- In my opinion, if it is a v2 only bug, we should not deal with it, do you agree?

**Comment by JeromeLeCoz** [comment]
Hi Ivan

I can't test this with v3 since this format cannot be imported, but I've not seen such a bug in v3 so far. So yes, let's forget about it.
