### ISSUE TITLE
Apparent disagreement in posterior display

### ISSUE THREAD

**Issue by JeromeLeCoz** [BaRatin-tools/BaRatinAGE#46]
Hi, something looks strange to me in the display of the k3 results in this example:
[Chiers_Chauvency.bar.zip](https://github.com/BaRatin-tools/BaRatinAGE/files/10661370/Chiers_Chauvency.bar.zip)

For instance, for the "S+2C_sans juillet 2021" rating curve, k3 = 1.4 +/-0.4 in the prior/post table and in the RC plot, but in the prior/post plot, the results look distributed like k3 = 1.8 +/-0.4...

For the "S+2C_juillet 2021" rating curve, the shift of the cenral value look even more obvious, as the k3 results follow the prior distribution (k3 = 1.4 +/-0.4) whereas the display is k3 = 1.2 +/-0.4...

Perhaps, this is due to discarded realizations (when k3<k2)? But then the statistics should not include the discarded values. I'm puzzled...

**Comment by IvanHeriver** [comment]
Hi @JeromeLeCoz , let me know if you also find the issue in v3. If you do not, I think you can close the issue.

**Comment by JeromeLeCoz** [comment]
There is actually no bug in v2 and v3, just my confusion of MaxPost and max of the marginal pdf of k3... which is fully clarified thanks to the excellent vizualisation offered by v3: 
<img width="199" alt="k3" src="https://github.com/BaRatin-tools/BaRatinAGE/assets/86300732/ad0b4bb8-e566-469e-94f3-b154c914eeac">

**Comment by JeromeLeCoz** [comment]
You can close the issue, brillantly solved by v3!

**Comment by IvanHeriver** [comment]
great! :)
