### ISSUE TITLE
Also display prior run results in a table

### ISSUE THREAD

**Issue by JeromeLeCoz** [BaRatin-tools/BaRatinAGE#55]
It would be useful to complete the prior rating curve tabs in the same way as the posterior rating curve  tabs (table, etc.).

**Comment by IvanHeriver** [comment]
Do you mean you'd like to have all the detailed resuts we have for the posterior rating curve also available for a prior rating curve?
- the plot
- the table
- the equation
- a plot of the prior distributions for each parameter
- table with a summary of the parameters (seems a bit irrelevant for a prior run)
- trace plots of the MC samples

Fitting all this in the current layout of a Hydraulic Configuration panel seems a bit challenging.

**Comment by JeromeLeCoz** [comment]
Not everything, just the table actually:

-     the plot: yes, as is
-     the table: yes, would be useful for plotting it out of the software
-     the equation: may not be very useful, we can skip I think
-     a plot of the prior distributions for each parameter: idem
-     table with a summary of the parameters (seems a bit irrelevant for a prior run): idem
-     trace plots of the MC samples: idem

It relates to how we could offer the possibility to compute a rating curve with no gaugings, or to use the prior RC to compute the hydrograph. I had proposed to include the prior RC in the RC list for computing the Q hydrograph, however it might be more logical to include the option "no gaugings" when creating a rating curve (I think BaM! can compute an RC with no obs, otherwise the prior RC could be taken as the posterior RC). Then we would have all the outputs of the RC available, and we could use that RC for computing the hydrograph.

**Comment by IvanHeriver** [comment]
This is indeed related to using no gaugings for a posterior run. I thought we has an issue on that matter but I don't seem to be able to find. A seperate issue should be opened I think.

As for the original matter of this issue, I agree with what you suggest and I'll rename the issue to "Also display prior run results in a table"

**Comment by IvanHeriver** [comment]
I'm in the process of fixing this issue. I am creating a prior result panel with the  rating curve plot and the rating table (instead of  only the rating curve plot). I am wondering, should I also include the "export to Bareme format" option? In the case of prior rating curves, instead of the total uncertainty, the parametric uncertainty would be used... Note that it is no extra work for me.

**Comment by JeromeLeCoz** [comment]
Hello, good point. I know cases in which importing the prior RC in Bareme/Jacinthe would be useful: the gaugings may be so uncertain that we use the prior RC to check them, rather than calibrating the posterior RC with them... Some users might be confused by this option, however the risk seems low to me. So, I'd say yes, if this is no extra work. It's also convenient for comparing the prior RC and the posterior RC in Barème (even though this will be possible in future versions of BaRatinAGE).

**Comment by IvanHeriver** [comment]
ok, great, thanks for the answer. I consider this issue completed, then.
