### ISSUE TITLE
Regional settings

### ISSUE THREAD

**Issue by JeromeLeCoz** [BaRatin-tools/BaRatinAGE#56]
In Options: choice of friction coefficient Manning/Strickler would be useful

Other regional settings such as stage and discharge units would be nice too, but it would require converting SI units (always used for computations) and the units displayed in the interface. Cf. related issue on converting units in import files.

**Comment by IvanHeriver** [comment]
I'm closing this issue since:
- Manning/strickler choice feature is discussed in issue #42 
- using other units that SI units is discussed in issue #28
