### ISSUE TITLE
Bugs d'affichage v2-2 chez CNR (Emeline)

### ISSUE THREAD

**Issue by JeromeLeCoz** [BaRatin-tools/BaRatinAGE#6]
Bug d’affichage sur pas mal de titres

    Bug sur l’échelle adaptative des contrôle à cocher/décocher

    Bug dans la fenêtre « autres graphiques », toutes les titres buguent et surtout les liens renvoient tous vers « comparer les paramètres a priori et a posteriori ».

**Comment by IvanHeriver** [comment]
I think all the issue described here refer to encoding issues which have now been resolved.

I'm closing this issue for now since I've not received any reports of similar bugs in the new 2.2 version.
