### ISSUE TITLE
Pb avec BaRatin surUBUNTU

### ISSUE THREAD

**Issue by Didier-FRANCOIS** [BaRatin-tools/BaRatinAGE#60]
Sur Ubuntu 22.04.4 LTS, BaRatinAGE fonctionne mais l'utilisation du bouton Exécuter provoque l'erreur suivante : "java.io.IOException: Cannot run program "/usr/local/BARATINAGE/bin/exe/BaRatin" (in directory "/usr/local/BARATINAGE/bin/exe"): error=13, Permission non accordée" avec l'affichage d'une fenêtre : "Problème d'écriture d'un fichier de configuration".
Les changements des droits d'exécution ont été appliqués comme précisé dans README.md : "sudo chmod a=rx BaRatinAGE" et "
sudo chmod a=rx BaRatin".

Merci pour votre aide.

**Comment by IvanHeriver** [comment]
Merci pour ce retour. D'après le message d'erreur que vous avez, vous utilisez la version 2.x du logiciel. La nouvelle version 3.0 devrait être utilisée à la place. Des projets de la version 2.x peuvent être importé. 

Pour télécharger la dernière version de BaRatinAGE: https://github.com/BaRatin-tools/BaRatinAGE/releases/latest
