### ISSUE TITLE
Languages in menu (options...change language) are unsorted

### ISSUE THREAD

**Issue by benRenard** [BaRatin-tools/BaRatinAGE#65]
It seems to be a linux-only problem, languages are in alphabetical order under windows.

Very minor, it's just a bit impractical

**Comment by JeromeLeCoz** [comment]
I think they are sorted by ISO code (at least for Windows?). Perhaps showing the ISO codes would help?

**Comment by IvanHeriver** [comment]
it is indeed sorted by language key (ISO code). I can change the text to be like

```
(fr) french - français
 ```

or sort using current or target local 

or both (add iso code + change sorting)

**Comment by JeromeLeCoz** [comment]
I vote for option 1:

(fr) french - français

**Comment by JeromeLeCoz** [comment]
but with a capital letter in English, not in French:

(fr) French - français

for all languages

**Comment by IvanHeriver** [comment]
The language names are actually part of Java, I have no control on how they are spelled but I checked, in english all languages have a capital first letter

**Comment by IvanHeriver** [comment]
done (see 50df44ecda725a4de6f980e5d8788b349a0c9025)
