### ISSUE TITLE
Open/save dialog are not translated

### ISSUE THREAD

**Issue by IvanHeriver** [BaRatin-tools/BaRatinAGE#7]
I noticed that the Open dialog (and probably all the other file related dialog) are always in english regardless of the computer's default locale and the language picked by the user. 

<img width="465" alt="open_bug" src="https://user-images.githubusercontent.com/62560360/200612786-1efbe983-3a25-4d92-86c9-3bbd3073be14.png">

It seems to be a known issue with Java Swing File dialog. I think this is worth fixing (although I don't know yet what's the best approach). In any case, it will require additional entries in dico.txt: 
- File name
- Look in
- View Menu
- Create New Folder
- Up One Level
- View
- Refresh
- New Folder
- List
- Details
- All Files

**Comment by JeromeLeCoz** [comment]
A corriger en effet, mais ça ne me semble pas bloquant non plus (tout le monde est habitué à naviguer ainsi).

Par contre, plusieurs ont été déstabilisés / étonnés que la fenêtre "Enregistrer" propose "Open" au lieu de "Save" pour enregistrer une étude...

**Comment by IvanHeriver** [comment]
I now use the save dialog instead of the open dialog where relevant (see commit dd461df9fc0f8e8260ed9e437a38f24f267ca0c4 ).

Since translation of these dialog box isn't fully addressed (only the title is translated I think) I leave the issue open. It will be addressed in futur version of BaRatinAGE.

**Comment by IvanHeriver** [comment]
My research led me to the idenifications of the following keys for the UI manager that need to be modified to correctly translate different part of the open and save dialog boxes. It is close to be exhaustive, but I believe there are still some missing pieces. Here it is using french translations:

```java
UIManager.put("FileChooser.openButtonText", "Ouvrir");
UIManager.put("FileChooser.lookInLabelText", "Rechercher dans");

UIManager.put("FileChooser.saveButtonText", "Sauvegarder");
UIManager.put("FileChooser.saveInLabelText", "Sauvegarder dans");

UIManager.put("FileChooser.cancelButtonText", "Annuler");
UIManager.put("FileChooser.cancelButtonToolTipText", "Annuler");

UIManager.put("FileChooser.fileNameLabelText", "Nom du fichier");
UIManager.put("FileChooser.filesOfTypeLabelText", "Type");
UIManager.put("FileChooser.acceptAllFileFilterText", "Tous les fichiers (*, *)");
UIManager.put("FileChooser.upFolderToolTipText", "Dossier parent");
UIManager.put("FileChooser.homeFolderToolTipText", "Bureau");
UIManager.put("FileChooser.newFolderToolTipText", "Créer un nouveau dossier");

UIManager.put("FileChooser.other.newFolder", "Nouveau");
UIManager.put("FileChooser.win32.newFolder", "Nouveau"); // default name of the folder

UIManager.put("FileChooser.refreshActionLabelText", "Actualiser");
UIManager.put("FileChooser.viewMenuLabelText", "Affichage");
UIManager.put("FileChooser.newFolderActionLabelText", "Nouveau dossier");

UIManager.put("FileChooser.renameErrorTitleText", "Impossible de renommer le fichier ou dossier");
UIManager.put("FileChooser.renameErrorText", "Impossible de renommer");
UIManager.put("FileChooser.renameErrorFileExistsText",
		"Un fichier ou dossier du même nom existe déjà ou le nom spécifié n'est pas valide");

UIManager.put("FileChooser.viewMenuToolTipText", "Affichage");
UIManager.put("FileChooser.listViewActionLabelText", "Liste");
UIManager.put("FileChooser.detailsViewActionLabelText", "Détails");
```
And there is also the following methods:
```java
chooser.setDialogTitle("Sauvegarder");
chooser.setApproveButtonToolTipText("Sauvegarder dans le fichier sélectionné");

```

**Comment by IvanHeriver** [comment]
fixed in v3.
