### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by JeromeLeCoz** [BaRatin-tools/BaRatinAGE#8]
L'iconique pipeau est irremplaçable mais quand on crée un raccourci Windows, la version en miroir ci-joint rend mieux : cf. capture écran ci-joint.

Je suggère de remplacer le fichier .ico avec le miroir.

[BaRatinAGE_icon.zip](https://github.com/BaRatin-tools/BaRatinAGE/files/9992398/BaRatinAGE_icon.zip)
<img width="156" alt="BaRatin_icons" src="https://user-images.githubusercontent.com/86300732/201398878-7ad0591f-e45d-43df-8344-ef4875b9ef82.png">

**Comment by IvanHeriver** [comment]
Done (see commit c08050f2bc97c0f7ebaad5825777ef66b72d222f)
