### ISSUE TITLE
Error in propagating prior coefficient for triangular weir

### ISSUE THREAD

**Issue by JeromeLeCoz** [BaRatin-tools/BaRatinAGE#82]
There must be a mistake in the propagation of the angle uncertainty since the computed standard deviation is way too high. Perhaps ommitted conversion from degrees to radian?

**Comment by IvanHeriver** [comment]
No conversions to radian were ommited as far as I can tell...

For the v3 implementation I used the v2 implementation as a reference. I've juste compared the implementations but I've failed to see any difference. Is this a bug that only affect BaRatinAGE v3? 

Note that in both v2 and v3 versions, implementations are quite difficult to read so I might have missed a mistake.

To further check for any mistake, it would be useful to have all the equations for all the controls written in a nice way  that I could use as a reference. Do you know if there's a pdf or something like that I could use?

**Comment by JeromeLeCoz** [comment]
The equations are displayed in the documentation, here: https://baratin-tools.github.io/en/doc/topics/hydraulic-controls/#determination-of-prior-parameters

In the attached spreadsheet, I don't find the same uncertainty u(a) (setting u(g)=u(Ct)=0) as in BaRatinAGE. It is much smaller. And with such values in k-a-c mode, the prior RC computes fine... u(nu) must be expressed in radians.
[propag_prior_Triangular_weir.xlsx](https://github.com/user-attachments/files/16933618/propag_prior_Triangular_weir.xlsx)

**Comment by IvanHeriver** [comment]
Thanks! I checked again and indeed, the conversion to radian of the uncertain value was ommited. It is also the case for the triangular channel by the way... **I'm fixing this right away!**

(in you excel sheet, there's a tiny typo: the uncertainty of the angle should be squared)

**Comment by JeromeLeCoz** [comment]
Thanks, Ivan, cool. I think that my spreadsheet is correct, not yours: the sensitivity coefficient has to be squared too, so that, for a single term, u(a) = sensitivity_coeff * u(nu)

The equation in the website documentation is correct too. We should also compare with what BaRatinAGE v2 yields.

**Comment by JeromeLeCoz** [comment]
For nu=170+/-20, BaRatinAGE v2 yields a=15.695 +/-31.5498, hence u(a)=15.7749, i.e. exactly the same result as in my spreadsheet. I also find the same result for nu=45+/-20.

**Comment by IvanHeriver** [comment]
> u(a) = sensitivity_coeff * u(nu)

of course! Sorry for the confusion!

And thanks for the comparison with BaRatinAGE v2!

**Comment by IvanHeriver** [comment]
Should now be fixed. I'm closing the issue.
